# Dockerfile.api
FROM python:3.11-slim

WORKDIR /app

RUN mkdir -p /tmp && chmod 1777 /tmp
ENV TMPDIR=/tmp

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "controller/api_controller.py"]