# Dockerfile.ftp
FROM python:3.11-slim

WORKDIR /app
ENV TMPDIR=/tmp
RUN mkdir -p /tmp
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 2121
EXPOSE 60000-60009

CMD ["python", "controller/ftp_server.py"]