# Dockerfile.aws
FROM python:3.11-slim

WORKDIR /app
RUN mkdir -p /tmp && chmod 1777 /tmp
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "-m", "controller.aws_listener"]