# Dockerfile.aws
FROM python:3.11-slim

WORKDIR /app
ENV TMPDIR=/tmp
RUN mkdir -p /tmp
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "-m", "controller.aws_listener"]