# Dockerfile.ftp
FROM python:3.11-slim

WORKDIR /app
RUN mkdir -p /tmp && chmod 1777 /tmp
ENV TMPDIR=/tmp
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 2121
EXPOSE 60000-60009

CMD ["python", "controller/ftp_server.py"]