# Dockerfile.api
FROM python:3.11

WORKDIR /app
ENV TMPDIR=/tmp
RUN mkdir -p /tmp && chmod 1777 /tmp
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "controller/api_controller.py"]